# Etapa 1: conseguir libs
FROM registry.access.redhat.com/ubi9-minimal AS libs
RUN microdnf install -y zlib ca-certificates && microdnf clean all

# Etapa final: UBI9-micro super liviano
FROM registry.access.redhat.com/ubi9-micro
WORKDIR /work
# zlib (y CA para HTTPS) desde la etapa anterior
COPY --from=libs /usr/lib64/libz.so.1* /usr/lib64/
COPY --from=libs /etc/pki/ca-trust /etc/pki/ca-trust
COPY target/*-runner /work/application
USER 10001
EXPOSE 8083
ENTRYPOINT ["./application"]
